name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4

      - uses: jontze/action-mdbook@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Check for broken links
        run: |
          curl -sSLo linkcheck.sh \
            https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
          # Cannot use --all here because of the generated redirect pages aren't available.
          sh linkcheck.sh book

      - name: Build with mdBook
        run: mdbook build

      - name: Deploy book
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./book
